### ISSUE TITLE
Hope to be a contributor

### ISSUE THREAD

**Issue by toptalent0921** [lifinance/contracts#845]
Dear Team.

I hope this message finds you well.
I'm from the Japan, and I'm a senior full stack blockchain developer with extensive experience in creating and implementing innovative blockchain solutions. After analyzing your GitHub and Discord channels, I'm impressed by the projects your team is working on and am eager to contribute my skills to your efforts.

I have a strong background in both front-end and back-end development, specializing in smart contracts, decentralized applications (dApps), and blockchain integration.

I'm enthusiastic about the opportunity to contribute to your projects and collaborate with your talented team.
I look forward to the possibility of working together and contributing to your exciting blockchain initiatives.

Best regards,

Tomoya Sakamoto
https://t.me/angrybird0921

**Comment by maxklenk** [comment]
Hey @toptalent0921,

we have a few open positions on our careers page. Please check them and apply if you see one that fits: https://li.fi/careers/

Best
~Max
